# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-12 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENT_NAME', models.CharField(max_length=200, verbose_name='企业名称')),
                ('DOM', models.CharField(max_length=500, verbose_name='经营地址')),
                ('REG_NO', models.CharField(max_length=100, verbose_name='企业注册号')),
                ('UNI_SCID', models.CharField(max_length=100, verbose_name='统一社会信用代码')),
                ('NEIGHBOR', models.CharField(max_length=100, verbose_name='街道')),
            ],
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='deptname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主责部门'),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='enterpriseinvoledname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='ttaskinfo',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise_case.Enterprise'),
        ),
    ]
