# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_case', '0003_auto_20181115_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttaskinfo',
            name='checkdelaytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='checkdeptbacktime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='createtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='delaytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='deptbacktime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='dispatchtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='percreatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='shangbaohechatime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='shangbaoheshitime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='solvingtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='stime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='supervisetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='telasktime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='xiafahechatime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttaskinfo',
            name='xiafaheshitime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
